name: Postman API Tests (Automated)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permite rodar manualmente pela aba Actions
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman e Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Executar testes via Postman API
        run: |
          newman run "https://api.postman.com/collections/23724069-846a9406-871f-417c-8848-ad9cef118" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          -r cli,htmlextra \
          --reporter-htmlextra-export report.html

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: report.html
